services: 
  sql:
    image: postgres:16
    container_name: testtoo-sql
    ports:
      # external : internal
      - 6432:5432
    volumes:
      - sql-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    restart: on-failure
    logging:
      options: 
        max-size: 10m
        max-file: 3
        
        
volumes:
  sql-volume:
    